require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'exe/*'

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/FormatStringToken:
  EnforcedStyle: template
